---
title: "Untitled"
author: "Zahier Nasrudin"
date: "5/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(dplyr)
library(readr)
library(reactable)
library(reactablefmtr)
library(htmltools)


```

```{r}

top_scorer <- read_csv("top_scorer.csv")

source("data_bar.r")


table_theme <- function() {
  reactable::reactableTheme(
    style = list(fontFamily = "Garamond", fontSize = "16px"),
    headerStyle = list(
      borderColor = "#333")
  )}






table <- reactable(top_scorer %>% select(-`Club(s) (Goals)`),
          theme = table_theme,
          columns = list(
            Rank = colDef(cell = icon_sets(top_scorer, colors = c("#0E1E5B", "#0E1E5B", "#0E1E5B"),
                                           icons = c("futbol", "futbol", "futbol"))),
            Player = colDef(details = function(index) {
              div(style = list(fontSize = 15, color = "#0E1E5B"), paste("Goals:",top_scorer[index, "Club(s) (Goals)"]))
            },
            width = 200),
            Goals = colDef(align = "left", # align column header
                              cell = data_bars(top_scorer, fill_color = c("#0E1E5B"),
                                               text_position = "outside-end")),
            Apps = colDef(align = "left", # align column header
                           cell = data_bars(top_scorer, fill_color = c("#0E1E5B"),
                                            text_position = "outside-end")),
            Ratio = colDef(align = "left", # align column header
                          cell = color_tiles(top_scorer, number_fmt = scales::percent,
                                             colors = c("lightpink", "white", "#bfeeff", "#96c5f1", "#6594C0")))),
          highlight = TRUE,
          searchable = TRUE)



div(class = "title",
  div("Table last updated on", format(Sys.Date(), "%b %d %Y"),
  table)
)



```

.title {

font-family: "Courier New";

font-size: 18px;

}
